runtime: php8

context:
  git:
    url: https://github.com/qnzjn123/PHP5.git
    ref: main

build:
  base: ubuntu
  command: |
    apt-get update
    apt-get install -y php-cli php-mysqli
    echo "PHP 프로젝트 빌드 완료"

run:
  command: php -S 0.0.0.0:${PORT:-8080} -t .

env:
  - name: PORT
    value: "8080"
  - name: DB_HOST
    value: localhost
  - name: DB_USER
    value: root
  - name: DB_PASS
    value: ""
  - name: DB_NAME
    value: board_db
