runtime: php74

context:
  git:
    url: https://github.com/qnzjn123/PHP5.git
    ref: main

build:
  command: |
    echo "PHP 프로젝트 빌드 완료"

run:
  command: php -S 0.0.0.0:$PORT

env:
  - name: DB_HOST
    value: localhost
  - name: DB_USER
    value: root
  - name: DB_PASS
    value: ""
  - name: DB_NAME
    value: board_db
