version: "1"
context:
  builder: maven
  buildpack: java
build:
  command: ./mvnw clean package -DskipTests
  output: target/*.jar
run:
  command: java -Xmx256m -Xms128m -Dserver.port=$PORT -jar target/board-1.0.0.jar
  port: 8080
