version: '3.8'

services:
  board-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-board
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    networks:
      - board-network

networks:
  board-network:
    driver: bridge
